apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-pusher-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-pusher-v2
  template:
    metadata:
      labels:
        app: location-pusher-v2
    spec:
      containers:
      - name: location-pusher-v2
        image: testregistrocontenedores.azurecr.io/location-pusher-v2:9566
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        resources:
          requests:
            cpu: 50m
            memory: 400Mi
          limits:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registrosatrack
---
apiVersion: v1
kind: Service
metadata:
  name: location-pusher-v2
  labels:
    app: location-pusher-v2
spec:
  type: LoadBalancer # Exposed over the internet through Azure Load Balancer
  sessionAffinity: ClientIP
  ports:
  - port: 80
  selector:
    app: location-pusher-v2
