apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeuirouting-stagin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeuirouting-stagin
  template:
    metadata:
      labels:
        app: homeuirouting-stagin
    spec:
      containers:
      - name: homeuirouting-stagin
        image: testregistrocontenedores.azurecr.io/home-routing:12013
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: UrlKeyCloak
          value: http://securityprovider.satrack.com:8080/auth/realms/satrack-base/protocol/openid-connect/token
        - name: UrlSecurity
          value: http://w2appsecurity.satrack.com/services/api/
        - name: UrlAllowedClients
          value: https://w2stohome.table.core.windows.net/  
        - name: TokenSTO
          value: sv=2018-03-28\u0026ss=t\u0026srt=o\u0026sp=rl\u0026se=2030-03-27T03:23:39Z\u0026st=2019-03-26T19:23:39Z\u0026spr=https,http\u0026sig=YHsHgho3GIe0ZECoZRsJYqmDw64rndsHGu8syfwkMcs%3D
        - name: UrlNw
          value: http://40.123.38.174/#
        - name: UrlLegacy
          value: http://webcloud2.satrack.com/
        - name: UrlContent
          value: www.satrack.com                                     
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registrosatrack
---
apiVersion: v1
kind: Service
metadata:
  name: homeuirouting-stagin
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: homeuirouting-stagin
